// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OpenClaw.Infrastructure.Common.Persistence;

#nullable disable

namespace OpenClaw.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318085519_AddWorkflowSystem")]
    partial class AddWorkflowSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OpenClaw.Domain.Chat.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Conversations", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Chat.Entities.ConversationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationMessages", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Configuration.Entities.AppConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean")
                        .HasColumnName("is_secret");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("uq_app_configs_key");

                    b.ToTable("app_configs", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Configuration.Entities.ChannelSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AllowedUserIds")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("allowed_user_ids");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("channel_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("EncryptedBotToken")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("encrypted_bot_token");

                    b.Property<string>("SecretToken")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("secret_token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id");

                    b.HasIndex("ChannelType")
                        .IsUnique()
                        .HasDatabaseName("ix_channel_settings_channel_type");

                    b.ToTable("channel_settings", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Configuration.Entities.ModelProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EncryptedApiKey")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("encrypted_api_key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_model_providers_is_active");

                    b.ToTable("model_providers", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Skills.Entities.SkillSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("skill_name");

                    b.HasKey("Id");

                    b.HasIndex("SkillName")
                        .IsUnique()
                        .HasDatabaseName("uq_skill_settings_skill_name");

                    b.ToTable("skill_settings", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("_permissions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("Permissions");

                    b.Property<string>("_roles")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("Roles");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Users.Entities.UserPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_preferences_user_id");

                    b.HasIndex("UserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("uq_user_preferences_user_key");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Workflows.Entities.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition_json");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scheduled_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("ScheduleJson")
                        .HasColumnType("text")
                        .HasColumnName("schedule_json");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId")
                        .HasDatabaseName("ix_workflow_definitions_created_by_user_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_workflow_definitions_is_active");

                    b.ToTable("workflow_definitions", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Workflows.Entities.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("InputJson")
                        .HasColumnType("text")
                        .HasColumnName("input_json");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text")
                        .HasColumnName("output_json");

                    b.Property<string>("PendingApprovalNodeId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pending_approval_node_id");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_definition_id");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_workflow_executions_started_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_workflow_executions_status");

                    b.HasIndex("WorkflowDefinitionId")
                        .HasDatabaseName("ix_workflow_executions_workflow_definition_id");

                    b.ToTable("workflow_executions", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Workflows.Entities.WorkflowNodeExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<string>("InputJson")
                        .HasColumnType("text")
                        .HasColumnName("input_json");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("node_id");

                    b.Property<string>("OutputJson")
                        .HasColumnType("text")
                        .HasColumnName("output_json");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid")
                        .HasColumnName("workflow_execution_id");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowExecutionId")
                        .HasDatabaseName("ix_workflow_node_executions_workflow_execution_id");

                    b.HasIndex("WorkflowExecutionId", "NodeId")
                        .IsUnique()
                        .HasDatabaseName("uq_workflow_node_executions_execution_node");

                    b.ToTable("workflow_node_executions", (string)null);
                });

            modelBuilder.Entity("OpenClaw.Domain.Chat.Entities.ConversationMessage", b =>
                {
                    b.HasOne("OpenClaw.Domain.Chat.Entities.Conversation", null)
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpenClaw.Domain.Workflows.Entities.WorkflowExecution", b =>
                {
                    b.HasOne("OpenClaw.Domain.Workflows.Entities.WorkflowDefinition", "WorkflowDefinition")
                        .WithMany("Executions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowDefinition");
                });

            modelBuilder.Entity("OpenClaw.Domain.Workflows.Entities.WorkflowNodeExecution", b =>
                {
                    b.HasOne("OpenClaw.Domain.Workflows.Entities.WorkflowExecution", "WorkflowExecution")
                        .WithMany("NodeExecutions")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("OpenClaw.Domain.Chat.Entities.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("OpenClaw.Domain.Workflows.Entities.WorkflowDefinition", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("OpenClaw.Domain.Workflows.Entities.WorkflowExecution", b =>
                {
                    b.Navigation("NodeExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
